version: '3.1'

services:
  thunderdome:
    image: thunderdome
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - asgard
    environment:
      APP_DOMAIN: ".127.0.0.1"
      COOKIE_SECURE: "false"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: thunderdome
      POSTGRES_USER: thor
      POSTGRES_PASSWORD: odinson
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - asgard

networks:
 asgard:

volumes:
  database_data:
